### PR TITLE
[feature] list ruby language vulnerabilities

### PR DESCRIPTION
**Pull request by jeremyolliver**
This is an attempt to implement #20 Feedback is certainly welcome, and needed on the format and file paths I've chosen.

Implementation:

I'm assuming that multiple platforms should be supported e.g. mri, jruby, rbx, and I've borrowed the format largely from the existing one for gems, replacing the `gem` attribute with `platform`

I've also changed the commonly used patch release syntax such as `1.9.3-p447` into `1.9.3.447` this is to make automated parsing by a tool similar to the way [bundler-audit](https://github.com/postmodern/bundler-audit) does for gems, that is, make use of `Gem::Version` (rubygems >= 1.8.0) which correctly handles comparisons using `~>` and other semantic operators on version strings with 4 numeric parts separated by periods.

I've also added almost all of the vulnerabilities listed on http://www.ruby-lang.org/en/security/ into [another feature branch](https://github.com/jeremyolliver/ruby-advisory-db/tree/feature/add-mri-vulnerabilities) which I can send a PR for if this format looks good - but I didn't want this pull request to get too big for now.

### CODE REVIEW

**Comment by reedloden** [comment]
Any update on this? Would love to have this, and would make a good starting point for trying to fix #165 as well.

**Comment by phillmv** [comment]
All we really need to do is settle on a schema, I think this languished out of inattention rather than lack of interest.

I'd be really down for keeping track of those as well.

**Comment by reedloden** [comment]
The most recent update uses `engine` to represent the interpreter and then uses a more parse-able format of the version (to deal with the crappy -p123 nonsense). I believe those are the only new things introduced here. Any objections to those two things? Otherwise, would be good to get this landed, and we can iterate as needed once we have the first consumer of this data (seems like modifying `bundler-audit` to test this would be a good first step).

**Comment by phillmv** [comment]
OK. I opened up an [new branch](https://github.com/rubysec/ruby-advisory-db/tree/ecosystem-vulns) off master and cherry picked @jeremyolliver's commits. 

I opened another PR in #166 to facilitate collaboration - I can merge things into that branch and edit them directly as opposed to PR commits into master.

**Pull request closed without merging**
