### PR TITLE
Add OSVDB-125675, OSVDB-125676, OSVDB-125677, and OSVDB-125678 for sidekiq

### PR DESCRIPTION
**Pull request by reedloden**
All affecting Sidekiq::Web

### CODE REVIEW

**Comment by reedloden** [comment]
Descriptions aren't super-detailed, but I'll go back and add more detailed ones later. The link to the PRs/issues should be enough for most people.

**Comment by phillmv** [comment]
Hrm, this advisory is making a great argument for settling for some alternate OSVDB id schema.

How about related_osvdb that takes a list?

**Comment by reedloden** [comment]
you mean like tying different OSVDB entries together? Only two of the four relate to the same issue.

but yeah... I worry that `related_osvdb` is too specific... I would like to have a more generic `references` that can have sub sections for other things, which could include other related OSVDBs.

**Comment by phillmv** [comment]
So my caveat with a generic `references` vs a specific `related_attribute_name_here`:

The specific schema will be easier to test, implement and change later if need be. We should be specific first and then abstract as we collect more uses, is my feeling.

Does that make sense?

**Comment by reedloden** [comment]
Fair enough... Can agree with that for a generic `references` thing, but what about just `related`?

Does it make sense to do:
``` lang=yaml
osvdb_related:
  - 12345
  - 67890

cve_related:
  - 2015-1234
  - 2014-5678
```

OR

``` lang=yaml
related:
  osvdb:
    - 12345
    - 67890

  cve:
    - 2015-1234
    - 2014-5678
```

**Comment by phillmv** [comment]
@reedloden settled for the more generic related :).

**Comment by reedloden** [comment]
Eh, I wish we kept the actual advisory in the case of multiple ones and relied on the consumers of the DB to ignore related ones... Otherwise, we're doing the users of our DB a disservice, as they may feel they have mitigated some issue, while the 'related' one still affects them.

**Comment by phillmv** [comment]
@reedloden in this case in particular, the only different bit of information that was different was the osvdb id.

If the title, description, url and patched version is identical then imho (full disclosure:  I'm biased as I maintain a downstream consumer of this db) all use cases are better off. We maintain "referential completeness" in terms of sourcing data and everyone knows what to do.

I think in future situations where there are two different bugs, and as a result there are two distinct things to mitigate then that makes total sense to keep them as separate. Otherwise it's just noise.

Does that make sense?

**Pull request merged**
