### PR TITLE
First pass at a rubysec id reservation scheme

### PR DESCRIPTION
**Pull request by mveytsman**
`rake reserve_id` reserves an id

`rake reserve_id[2012]` reserves an id in 2012

### CODE REVIEW

**Comment by postmodern** [comment]
How do we avoid collisions where two contributors reserve the same ID?

**Comment by mveytsman** [comment]
My assumption was that you do the reservation in an earlier commit/PR and handle merge conflicts by hand. 

Can you think of a better way?

**Comment by postmodern** [comment]
Also do we really need a CVE-like ID for advisories? Advisories are currently grouped by effected gem or ruby, so the IDs would only need to be unique in that scope.

**Comment by mveytsman** [comment]
My worry about scoping to gem is the edge case when gems change names.

**Comment by postmodern** [comment]
Ah, well the previously released versions of those gems would still have the same name. So we'd just make a new directory for the new gem name.

**Comment by mveytsman** [comment]
Closing this see #224

**Pull request closed without merging**
