### PR TITLE
Update rest-client entry to reflect patch.

### PR DESCRIPTION
**Pull request by aselder**
This issue was addressed in 1.7.3

### CODE REVIEW

**Comment by phillmv** [comment]
@aselder hey! I believe you, but given the lack of info on the osvdb link, would you happen to have a link confirming this in the repo?

Many thanks,

**Comment by aselder** [comment]
https://github.com/rest-client/rest-client/blob/master/history.md

**Comment by derekprior** [comment]
The specific reported issue in the (poorly reported) OSVDB has indeed been adressed. Be cool to get this in.

**Comment by derekprior** [comment]
sorry, forgot the commit link: https://github.com/rest-client/rest-client/commit/60ae4a5373e574bdeacd7b526c72f4e7d0ca858f

**Comment by phillmv** [comment]
I thought I'd merged this in yesterday. Thanks!

**Pull request merged**
