### PR TITLE
Added activesupport, jquery-rails, rack, web-console disclosures.

### PR DESCRIPTION
**Pull request by phillmv**
@skorth @mveytsman pls review <3

### CODE REVIEW

**Comment by f3ndot** [comment]
LGTM :+1:

**Comment by dannyfallon** [comment]
Missing one, I think - https://gist.github.com/tenderlove/f2a606459f6027f583c9

**Comment by f3ndot** [comment]
@dannyfallon good catch, that hasn't hit my inbox yet from the announce

**Comment by mveytsman** [comment]
Good catch @dannyfallon, just added it to the PR.

**Comment by mveytsman** [comment]
And I made a typo already :) 

Someone who's not me please review.

**Comment by phillmv** [comment]
@mveytsman for 3227 add in the workaround to the text.

**Comment by phillmv** [comment]
OK, everything seems to check out. Thanks @f3ndot and @dannyfallon and @presidentbeef on twitter

**Comment by dannyfallon** [comment]
:+1: :tada:

**Pull request merged**
