### PR TITLE
docs: fix broken link for OSVDB

### PR DESCRIPTION
**Pull request by lirantal**
README link was broken.

### CODE REVIEW

**Review by reedloden — CHANGES_REQUESTED** [review]
OSVDB is correct here. Perhaps we should update the URL to be https://en.wikipedia.org/wiki/Open_Source_Vulnerability_Database instead.

**Comment by lirantal** [comment]
Is that still relevant though? I was under the impression that this is part of the vulnerabilities sourced into ruby-advisory-db but if that doesn't exist anymore should we just remove it entirely?

**Comment by postmodern** [comment]
Google's OSV.dev is entirely different from the old OSVDB (where Open Source is meant to refer to Open Source Intelligence, not Open Source Software).

**Comment by phillmv** [comment]
> Is that still relevant though? I was under the impression that this is part of the vulnerabilities sourced into ruby-advisory-db but if that doesn't exist anymore should we just remove it entirely?

Looks like we still use `osvdb` ids [for really old vulns](https://github.com/rubysec/ruby-advisory-db/blob/9f906cf530f23986f07cfee5230b3f2e5779aedb/gems/as/OSVDB-112683.yml#L3)

I second Reed's suggestion for pointing the URL to the wiki page 😃.

**Review by reedloden — APPROVED** [review]

**Pull request merged**
