### PR TITLE
Created draft of OSVDB-96396.yml advisory

### PR DESCRIPTION
**Pull request by jasnow**
Created draft of OSVDB-96396.yml advisory to support issue #178.

### CODE REVIEW

**Comment by postmodern** [comment]
Manually cherry-picked 8b652b606eb6737365a5d54492170ca42018314a into master.

**Comment by jmadkins** [comment]
Greetings 👋 

Just an FYI: I'm now receiving the following error when running `bundler audit` but I'm unsure how to proceed.

```
Name: activemodel
Version: 7.0.5
Criticality: Unknown
URL: https://github.com/rails/rails/pull/8122
Title: Don't allow confirmation to pass if confirmation value is nil and doesn't match value.
Solution: remove or disable this gem until a patch is available!

Vulnerabilities found!
```

**Comment by jmadkins** [comment]
I've opened #612 to discuss this further.

**Comment by postmodern** [comment]
@jasnow looks like you forgot to add `patched_versions:` which caused it to flag everything. Will need to re-submit with a `patched_versions:` or abandon OSVDB-96396 as incomplete.

**Pull request closed without merging**
