### PR TITLE
Fix patched version for GHSA-2qc6-mcvw-92cw

### PR DESCRIPTION
**Pull request by padde**
> FYI - This PR duplicates #519

Oh well it popped up while I was writing this. Closing in favor of #519

### CODE REVIEW

**Comment by dobrite** [comment]
Just hit this too 😅

**Comment by Nandez89** [comment]
Same here can we update this please 👍

**Comment by markwilliamson503** [comment]
Same for us.

**Review by davidpaniz — APPROVED** [review]

**Comment by markwilliamson503** [comment]
FYI - This PR duplicates https://github.com/rubysec/ruby-advisory-db/pull/519

**Pull request closed without merging**
