### PR TITLE
Attempt to generate `patched_versions` from GHSA `firstPatchedVersion`.

### PR DESCRIPTION
**Pull request by postmodern**
Attempt to automatically generate the `patched_versions` from the GHSA `vulnerabilities`/`firstPatchedVersion`/`identiifer` information.

### CODE REVIEW

**Comment by postmodern** [comment]
@jasnow since I don't have the GitHub sync OAuth token setup locally, could you test this branch and see if it can correctly generate `patched_versions` for new GHSA advisories?

**Comment by jasnow** [comment]
* Added comma at end of line 379:  "patched_versions" => patched_versions_for(package).
 * Working on this:
 ```
 NoMethodError: undefined method `[]' for nil:NilClass

          first_patched_versions << v['firstPatchedVersion']['identifier']
````

**Comment by postmodern** [comment]
@jasnow interesting, looks like not all `vulnerabilities` have `firstPatchedVersion` key, which makes sense since some vulnerabilities will be unpatched.

**Comment by jasnow** [comment]
Noticed that you use double quotes were used inside "[]"s elsewhere in the script.

**Comment by jasnow** [comment]
I will start testing this PR today. Here are some of my test cases: https://gist.github.com/jasnow/7c99f4d9e8b838293ba407af373141af

**Pull request merged**
