### PR TITLE
Removing patched version for Redcloth Gem

### PR DESCRIPTION
**Pull request by greggawatt**
Patched version is wrong as version 4.3.2 still has XSS issues, There is no currently patched version.

### CODE REVIEW

**Comment by greggawatt** [comment]
proof: https://github.com/jgarber/redcloth/issues/46

**Comment by VanessaHenderson** [comment]
Under this circumstances in the past wouldn't a new CVE be requested since this CVE is from 2012?

**Comment by mveytsman** [comment]
I don't think this is an issue as stated: https://github.com/jgarber/redcloth/issues/46#issuecomment-361655921

**Comment by greggawatt** [comment]
I agree with @mveytsman's assessment.

**Pull request closed without merging**
