### PR TITLE
Relax requirements for ActiveJob in CVE 2018-16476

### PR DESCRIPTION
**Pull request by mjankowski**
With the release of Rails 5.1.7 this advisory is coming up as a vulnerability, even though the fix is in place in 5.1.7.

This change relaxes the requirement to include versions greater than but outside of the 5.1.6.x series.

### CODE REVIEW

**Comment by aselder** [comment]
👍 please

**Comment by mjankowski** [comment]
Ah good catch, I'll revise.

**Comment by mjankowski** [comment]
Updated to add 5.1.7 and leave the 5.1.6 line in place.

**Comment by reedloden** [comment]
Makes sense. Thanks!

**Pull request merged**
